apiVersion: v1
kind: Secret
metadata:
  name: apex-db-secret
  namespace: apex
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://apexadmin:apexpass10203040@apex-postgres.postgres.database.azure.com:5432/postgres"
