apiVersion: v1
kind: Service
metadata:
  name: apex-app-service
  namespace: apex
spec:
  selector:
    app: apex-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
